/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package proje;

import java.awt.Component;
import java.awt.PopupMenu;
import java.io.BufferedReader;
import java.io.BufferedWriter;
import java.io.File;
import java.io.FileNotFoundException;
import java.io.FileOutputStream;
import java.io.FileReader;
import java.io.FileWriter;
import java.io.IOException;
import java.io.ObjectOutputStream;
import java.io.PrintWriter;
import java.util.ArrayList;
import java.util.Scanner;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.AbstractListModel;
import javax.swing.DefaultListModel;
import javax.swing.ListSelectionModel;

/**
 *
 * @author feras
 */
public class MainPage extends javax.swing.JFrame {

    NewEntry newEntry = new NewEntry();
    static int commentNum = 0; /// static yapma amacım her jhangi bir yerde değerini değişitirebilmek ve sonra, önce butonlerinde kullanabilmek için
    Entry entry1 = new Entry(" ", " ");
    newComment yeniYorum = new newComment();
    DefaultListModel model = new DefaultListModel();
    ArrayList<Entry> importentryList = new ArrayList<>();
    Entry importEntry = new Entry();

    public MainPage() {
        initComponents();
        JListSettings();
    }

    public void addElementToList(String a) {
        model.addElement(a);

    }

    public void WelcomeMessege(String a) {
        LableMainWelcome.setText(a + " Hoşgeldiniz");
    }

    public void JListSettings() { //Jlist ayarlamalrı
        newEntry.setList(jList1, model, importentryList); //listi NewEntry sinifi ile bağladık
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jList1 = new javax.swing.JList<>();
        LableMainWelcome = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jTextFieldTitle = new javax.swing.JTextField();
        BtnLike = new javax.swing.JButton();
        BtnShare = new javax.swing.JButton();
        BtnUnlike = new javax.swing.JButton();
        jLabelLike = new javax.swing.JLabel();
        jLabelshare = new javax.swing.JLabel();
        jLabelUnlike = new javax.swing.JLabel();
        jBtnImport = new javax.swing.JButton();
        jBtnExport = new javax.swing.JButton();
        lableLike = new javax.swing.JLabel();
        lableUnLike = new javax.swing.JLabel();
        lableShare = new javax.swing.JLabel();
        jBtnSonra = new javax.swing.JButton();
        jBtnOnce = new javax.swing.JButton();
        jBtnYorum = new javax.swing.JButton();
        jLabelYazar = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTextPane1 = new javax.swing.JTextPane();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        jList1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jList1.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jList1.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                jList1ValueChanged(evt);
            }
        });
        jScrollPane1.setViewportView(jList1);

        LableMainWelcome.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N

        jButton1.setText("Entery Ekle");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("Entery Sil");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jTextFieldTitle.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jTextFieldTitle.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldTitleActionPerformed(evt);
            }
        });

        BtnLike.setText("Like");
        BtnLike.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnLikeActionPerformed(evt);
            }
        });

        BtnShare.setText("Share");
        BtnShare.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnShareActionPerformed(evt);
            }
        });

        BtnUnlike.setText("UnLilke");
        BtnUnlike.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnUnlikeActionPerformed(evt);
            }
        });

        jBtnImport.setText("import");
        jBtnImport.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnImportActionPerformed(evt);
            }
        });

        jBtnExport.setText("Export");
        jBtnExport.setToolTipText("");
        jBtnExport.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnExportActionPerformed(evt);
            }
        });

        lableLike.setForeground(new java.awt.Color(0, 0, 204));
        lableLike.setText("jLabel1");

        lableUnLike.setForeground(new java.awt.Color(0, 0, 204));
        lableUnLike.setText("jLabel2");

        lableShare.setForeground(new java.awt.Color(0, 0, 204));
        lableShare.setText("jLabel3");

        jBtnSonra.setText("< Sonraki");
        jBtnSonra.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnSonraActionPerformed(evt);
            }
        });

        jBtnOnce.setText("Önceki >");
        jBtnOnce.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnOnceActionPerformed(evt);
            }
        });

        jBtnYorum.setText("Yorum Ekle");
        jBtnYorum.setToolTipText("");
        jBtnYorum.setActionCommand("");
        jBtnYorum.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnYorumActionPerformed(evt);
            }
        });

        jLabelYazar.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabelYazar.setText("jLabel1");

        jTextPane1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jScrollPane2.setViewportView(jTextPane1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(261, 261, 261)
                        .addComponent(jLabelLike, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(40, 40, 40)
                        .addComponent(jLabelshare, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(38, 38, 38)
                        .addComponent(jLabelUnlike, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 348, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(lableLike, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(BtnLike, javax.swing.GroupLayout.Alignment.LEADING))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(BtnUnlike, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(lableUnLike, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(BtnShare, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(lableShare, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(66, 66, 66)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(472, 472, 472)
                                .addComponent(jLabelYazar, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(38, 38, 38)
                                .addComponent(jBtnSonra)
                                .addGap(18, 18, 18)
                                .addComponent(jBtnOnce)
                                .addGap(18, 18, 18)
                                .addComponent(jBtnYorum))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(jTextFieldTitle, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 586, Short.MAX_VALUE))))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jBtnImport)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jBtnExport)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButton2)))
                .addContainerGap(52, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(52, 52, 52)
                .addComponent(LableMainWelcome, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(LableMainWelcome, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(25, 25, 25)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 308, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(62, 62, 62)
                        .addComponent(jTextFieldTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 256, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lableLike)
                                .addGap(6, 6, 6)
                                .addComponent(BtnLike))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lableUnLike)
                                .addGap(6, 6, 6)
                                .addComponent(BtnUnlike))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lableShare, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(jBtnYorum)
                                        .addComponent(jBtnSonra)
                                        .addComponent(jBtnOnce))
                                    .addComponent(BtnShare))))
                        .addGap(19, 19, 19)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jBtnImport)
                            .addComponent(jBtnExport)
                            .addComponent(jButton1)
                            .addComponent(jButton2))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 33, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabelLike)
                            .addComponent(jLabelshare)
                            .addComponent(jLabelUnlike)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabelYazar)
                        .addContainerGap())))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        newEntry.setVisible(true);
        //   Entry newEntry= new Entry(Title, subject);

    }//GEN-LAST:event_jButton1ActionPerformed

    private void jList1ValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_jList1ValueChanged
        entry1 = newEntry.entryList.get(jList1.getSelectedIndex());
     
        
        jTextFieldTitle.setText(entry1.Title);
        if (entry1.commentArray.size() > 0) {
            jTextPane1.setText(entry1.commentArray.get(0).yorum);
            jLabelYazar.setText("Yazar: " + entry1.commentArray.get(0).yazar);
        } else {
            jTextPane1.setText("Bu Entry'e yorum yapılmadı");
        }
        commentNum = 0; // commenleri baştan göstermek için
        lableLike.setText(newEntry.entryList.get(jList1.getSelectedIndex()).likeiNumber + " like"); // değişim olduğu zaman like bilgileri da değişsin
        lableUnLike.setText(newEntry.entryList.get(jList1.getSelectedIndex()).sahreNumber + " Share");// yukarda yapılan şeyin aynısı burada
        lableShare.setText(newEntry.entryList.get(jList1.getSelectedIndex()).UnlikeiNumber + " Unlike");


    }//GEN-LAST:event_jList1ValueChanged

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed

        newEntry.removeEntry(jList1.getSelectedIndex());
    }//GEN-LAST:event_jButton2ActionPerformed

    private void BtnLikeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnLikeActionPerformed

        int enteryNumber = jList1.getSelectedIndex();
        newEntry.entryList.get(enteryNumber).likeiNumber++; // like sayısı arttırmak
        lableLike.setText(newEntry.entryList.get(enteryNumber).likeiNumber + " like");
    }//GEN-LAST:event_BtnLikeActionPerformed

    private void BtnShareActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnShareActionPerformed
        int enteryNumber = jList1.getSelectedIndex();
        newEntry.entryList.get(enteryNumber).sahreNumber++; // like sayısı arttırmak
        lableShare.setText(newEntry.entryList.get(enteryNumber).sahreNumber + " Share");

    }//GEN-LAST:event_BtnShareActionPerformed

    private void BtnUnlikeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnUnlikeActionPerformed
        int enteryNumber = jList1.getSelectedIndex();
        newEntry.entryList.get(enteryNumber).UnlikeiNumber++; // like sayısı arttırmak
        lableUnLike.setText(newEntry.entryList.get(enteryNumber).UnlikeiNumber + " Unlike");

    }//GEN-LAST:event_BtnUnlikeActionPerformed

    private void jBtnImportActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnImportActionPerformed

        String dosyaYolu = "C:\\Users\\feras\\Desktop\\sonuc.txt";
        File sourceFile = new File(dosyaYolu);
        String Etitle;
        String ESubject;
        String Elike0;
        String EUnlike0;
        String Eshare0;
        String Yazar = "";
        String Yorum = "";
        // String sonSatir="";       

        try {
            Scanner input = new Scanner(sourceFile);

            while (input.hasNextLine()) {

                Etitle = (input.nextLine());
                ESubject = (input.nextLine());
                Elike0 = (input.nextLine());
                EUnlike0 = (input.nextLine());
                Eshare0 = (input.nextLine());

                importEntry = new Entry(Etitle, ESubject, Elike0, EUnlike0, Eshare0);
                ArrayList<Comment> importYorumList = new ArrayList<>();

                Yazar = (input.nextLine()); //entrynin son satiri olup olmadığın kontrolu
                int test = 0;

                while (!Yazar.equals("FER")) { // tüm yorumları almak için 
                    if (test > 0) {
                        Yazar = (input.nextLine());
                    }
                    if (Yazar.equals("FER")) {
                        break;
                    } else {
                        Yorum = (input.nextLine());
                        Comment yorumObject = new Comment(Yazar, Yorum);
                        importYorumList.add(yorumObject);
                        test = 1;
                    }
                    importEntry.commentArray = importYorumList;
                }
                importentryList.add(importEntry);
            }

        } catch (FileNotFoundException ex) {
            System.out.println("dosyayı bulamdım " + ex.getMessage());

        }
                for (int i = 0; i < importentryList.size(); i++) {
                    model.addElement(importentryList.get(i).Title);
                }

    }//GEN-LAST:event_jBtnImportActionPerformed


    private void jBtnExportActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnExportActionPerformed
        String dosyaYolu2 = "C:\\Users\\feras\\Desktop\\sonuc.txt";
        File tagetFile = new File(dosyaYolu2);

        for (int i = 0; i < newEntry.entryList.size(); i++) {

            try {
                PrintWriter writer = new PrintWriter(new FileWriter(tagetFile, true));
// true olduğu zaman üstüne yazıyor ve false olduğu zaman sıfırdan yazıyor.
                writer.println(newEntry.entryList.get(i).Title);
                writer.println(newEntry.entryList.get(i).subject);
                writer.println(newEntry.entryList.get(i).likeiNumber);
                writer.println(newEntry.entryList.get(i).UnlikeiNumber);
                writer.println(newEntry.entryList.get(i).sahreNumber);
                int test = 0;

                
                
                for (int j = 0; j < newEntry.entryList.get(i).commentArray.size(); j++) {
                    writer.println(newEntry.entryList.get(i).commentArray.get(j).yazar);
                    writer.println(newEntry.entryList.get(i).commentArray.get(j).yorum);
                }
                writer.println("FER");
                writer.flush();

            } catch (FileNotFoundException e) {

                System.out.println("yazma işlem yapılamadı");
            } catch (IOException ex) {
                Logger.getLogger(MainPage.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
        tagetFile.exists();

    }//GEN-LAST:event_jBtnExportActionPerformed

    private void jTextFieldTitleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldTitleActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldTitleActionPerformed

    private void jBtnYorumActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnYorumActionPerformed
        int test = jList1.getSelectedIndex();
        yeniYorum.setVisible(true);
        yeniYorum.setCommentArray(importentryList.get(test).commentArray);
    }//GEN-LAST:event_jBtnYorumActionPerformed

    private void jBtnSonraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnSonraActionPerformed
        entry1 = newEntry.entryList.get(jList1.getSelectedIndex());
        if (commentNum < entry1.commentArray.size() - 1) {
            commentNum++;
            jTextPane1.setText(entry1.commentArray.get(commentNum).yorum);
            jLabelYazar.setText("Yazar: " + entry1.commentArray.get(commentNum).yazar);

        }
    }//GEN-LAST:event_jBtnSonraActionPerformed

    private void jBtnOnceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnOnceActionPerformed
        entry1 = newEntry.entryList.get(jList1.getSelectedIndex());
        if (commentNum > 0) {
            commentNum--;
            jTextPane1.setText(entry1.commentArray.get(commentNum).yorum);
            jLabelYazar.setText("Yazar: " + entry1.commentArray.get(commentNum).yazar);

        }
    }//GEN-LAST:event_jBtnOnceActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainPage().setVisible(true);  /// false olması lazım çünkü login yapınca çalışacaktır.

            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtnLike;
    private javax.swing.JButton BtnShare;
    private javax.swing.JButton BtnUnlike;
    private javax.swing.JLabel LableMainWelcome;
    private javax.swing.JButton jBtnExport;
    private javax.swing.JButton jBtnImport;
    private javax.swing.JButton jBtnOnce;
    private javax.swing.JButton jBtnSonra;
    private javax.swing.JButton jBtnYorum;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabelLike;
    private javax.swing.JLabel jLabelUnlike;
    private javax.swing.JLabel jLabelYazar;
    private javax.swing.JLabel jLabelshare;
    private javax.swing.JList<String> jList1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextField jTextFieldTitle;
    private javax.swing.JTextPane jTextPane1;
    private javax.swing.JLabel lableLike;
    private javax.swing.JLabel lableShare;
    private javax.swing.JLabel lableUnLike;
    // End of variables declaration//GEN-END:variables
}
